package App::EventStreamr::DVswitch::Youtube::DVfifo;
use Method::Signatures;
use Moo;
use namespace::clean;

# ABSTRACT: A Youtube fifo process

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

This Provides a Youtube dvfifo process.

=head1 DESCRIPTION

This largely extends L<App::EventStreamr::Process>, provides
default cmds that can be overridden in the configuration.

=cut

extends 'App::EventStreamr::Process';

has 'cmd'         => ( is => 'ro', default => sub { '/usr/local/bin/dvfifo.sh' } );
has 'id'          => ( is => 'ro', required => 1 );
has 'type'        => ( is => 'ro', default => sub { 'youtube' } );

with('App::EventStreamr::DVswitch::Roles::MixerWait');

1;
